### ISSUE TITLE
Signature of Register…Server in generated files

### ISSUE THREAD

**Issue by TheCount** [jsmouret/grpc-over-webrtc#1]
Hey @jsmouret, cool stuff!

Sorry if I'm overlooking something obvious, but in your repo, the generated function signatures, e. g., in https://github.com/jsmouret/grpc-over-webrtc/blob/master/server/protos/echo/echo.pb.go#L595, expect an `interface { RegisterService(*grpc.ServiceDesc, interface{}) }`. When I try to generate code, the same function expects a `*grpc.Server`, which of course isn't helpful if I want to pass a WebRTC proxy instead. Did you change the generated file by hand, or am I missing something obvious in the generator options?

Thanks!

**Comment by jsmouret** [comment]
Yes, there is a nasty little trick there:
https://github.com/jsmouret/grpc-over-webrtc/blob/master/server/proto.sh#L22

**Comment by TheCount** [comment]
> Yes, there is a nasty little trick there:
> https://github.com/jsmouret/grpc-over-webrtc/blob/master/server/proto.sh#L22

Ahh, got it, I missed that, thank you!
