### ISSUE TITLE
generator

### ISSUE THREAD

**Issue by joe-getcouragenow** [jsmouret/grpc-over-webrtc#2]
I have not dived into the code too deeply, but a code generator that is Protobuf driven might be useful here ?

https://github.com/moul/protoc-gen-gotemplate

It even has a Web based real time ide: http://protoc-gen-gotemplate.m.42.am/

**Comment by jsmouret** [comment]
I was hoping to only rely on standard tools but, if need be, that generator may come handy.
Thanks for link :)

**Comment by joe-getcouragenow** [comment]
I knwo, but this is bleeding edge. The GPRC Team is looking to support your functionality but its a long way off for now.

**Comment by jsmouret** [comment]
The only required tweak is to adjust the RegisterService signature, as mentioned in #1
And that's not a change big enough to introduce a different generator that would require extra work to keep in sync with the official one.

**Comment by joe-getcouragenow** [comment]
> The only required tweak is to adjust the RegisterService signature, as mentioned in #1

Awesome - that makes sense. Really helpful !!

> And that's not a change big enough to introduce a different generator that would require extra work to keep in sync with the official one.

i agree with you about not introducing another generator.

Will close - thanks @jsmouret
