### ISSUE TITLE
Further/expanded work on this library

### ISSUE THREAD

**Issue by edaniels** [jsmouret/grpc-over-webrtc#61]
Hey! Just wanted to leave a note that I've done a lot of work over on https://github.com/viamrobotics/goutils/tree/main/rpc/examples/echo which adds grpc over webrtc that we've been using at production levels for about a year now. It includes a signaling server implementation via in-memory or MongoDB. This repo is of course credited with the original idea!

**Comment by jsmouret** [comment]
Very happy to hear that the idea is spreading :)
Thank you!
